
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class LoginCine extends javax.swing.JFrame {

    /**
     * Creates new form LoginCine
     */
    public LoginCine() {
        initComponents();
        input_password.setBackground(new Color(18,30,49));
        input_password.setForeground(Color.WHITE);
        input_user.setBackground(new Color(18,30,49));
        input_user.setForeground(Color.WHITE);
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg_cine = new javax.swing.JLabel();
        Parent_panel_login = new javax.swing.JPanel();
        logo_login = new javax.swing.JLabel();
        tx_iniciarsesion = new javax.swing.JLabel();
        tx_user = new javax.swing.JLabel();
        input_user = new javax.swing.JTextField();
        tx_password = new javax.swing.JLabel();
        input_password = new javax.swing.JPasswordField();
        ingreso_button = new javax.swing.JButton();
        tx_descripcion = new javax.swing.JLabel();
        registro_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bg_cine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Cine.jpg"))); // NOI18N
        Bg_cine.setText("jLabel1");
        Bg_cine.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Parent_panel_login.setBackground(new java.awt.Color(0, 51, 102));
        Parent_panel_login.setForeground(new java.awt.Color(0, 51, 102));

        logo_login.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        logo_login.setForeground(new java.awt.Color(255, 204, 102));
        logo_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Logo.png"))); // NOI18N
        logo_login.setText("Cine Andino");

        tx_iniciarsesion.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        tx_iniciarsesion.setForeground(new java.awt.Color(255, 204, 102));
        tx_iniciarsesion.setText("Iniciar Sesión");

        tx_user.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        tx_user.setForeground(new java.awt.Color(255, 204, 102));
        tx_user.setText("Usuario");

        input_user.setFont(new java.awt.Font("Roboto Black", 2, 14)); // NOI18N
        input_user.setText("Ingrese su Correo Electronico");
        input_user.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        input_user.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_userMousePressed(evt);
            }
        });

        tx_password.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        tx_password.setForeground(new java.awt.Color(255, 204, 102));
        tx_password.setText("Contraseña");

        input_password.setFont(new java.awt.Font("Roboto Black", 2, 14)); // NOI18N
        input_password.setText("******");
        input_password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        input_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_passwordMousePressed(evt);
            }
        });

        ingreso_button.setBackground(new java.awt.Color(255, 51, 51));
        ingreso_button.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        ingreso_button.setForeground(new java.awt.Color(255, 204, 102));
        ingreso_button.setText("Entrar");
        ingreso_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ingreso_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingreso_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreso_buttonActionPerformed(evt);
            }
        });

        tx_descripcion.setFont(new java.awt.Font("Cambria Math", 3, 14)); // NOI18N
        tx_descripcion.setForeground(new java.awt.Color(255, 102, 102));
        tx_descripcion.setText("\"Donde la experiencia es de otro mundo...\"");

        registro_button.setBackground(new java.awt.Color(255, 51, 51));
        registro_button.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        registro_button.setForeground(new java.awt.Color(255, 204, 102));
        registro_button.setText("Registrarse");
        registro_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        registro_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registro_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registro_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Parent_panel_loginLayout = new javax.swing.GroupLayout(Parent_panel_login);
        Parent_panel_login.setLayout(Parent_panel_loginLayout);
        Parent_panel_loginLayout.setHorizontalGroup(
            Parent_panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Parent_panel_loginLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(logo_login, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Parent_panel_loginLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(Parent_panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Parent_panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(input_user)
                        .addComponent(input_password, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tx_user, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tx_password, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Parent_panel_loginLayout.createSequentialGroup()
                            .addComponent(ingreso_button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(registro_button, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tx_iniciarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tx_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        Parent_panel_loginLayout.setVerticalGroup(
            Parent_panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Parent_panel_loginLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(logo_login)
                .addGap(18, 18, 18)
                .addComponent(tx_descripcion)
                .addGap(22, 22, 22)
                .addComponent(tx_iniciarsesion)
                .addGap(18, 18, 18)
                .addComponent(tx_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input_user, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tx_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input_password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Parent_panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingreso_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registro_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Parent_panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Bg_cine, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Parent_panel_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Bg_cine, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingreso_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreso_buttonActionPerformed
        InterfazCine interfazCine = new InterfazCine(); // Abre la segunda pantalla
        dispose(); // Cierra la pantalla actual
        interfazCine.setVisible(true);
    }//GEN-LAST:event_ingreso_buttonActionPerformed

    private void input_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_userMousePressed
        
        if(input_user.getText().equals("Ingrese su Correo Electronico")){
            input_user.setText("");
        }
        if(String.valueOf(input_password.getPassword()).isEmpty()){
            input_password.setText("******");
        }
    }//GEN-LAST:event_input_userMousePressed

    private void input_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_passwordMousePressed
      
        if(String.valueOf(input_password.getPassword()).equals("******")){
            input_password.setText("");
        }
        if(input_user.getText().isEmpty()){
            input_user.setText("Ingrese su Correo Electronico");
        }
    }//GEN-LAST:event_input_passwordMousePressed

    private void registro_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registro_buttonActionPerformed
        SignupCine signupCine = new SignupCine(); // Abre la segunda pantalla
        dispose(); // Cierra la pantalla actual
        signupCine.setVisible(true);
    }//GEN-LAST:event_registro_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginCine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg_cine;
    private javax.swing.JPanel Parent_panel_login;
    private javax.swing.JButton ingreso_button;
    private javax.swing.JPasswordField input_password;
    private javax.swing.JTextField input_user;
    private javax.swing.JLabel logo_login;
    private javax.swing.JButton registro_button;
    private javax.swing.JLabel tx_descripcion;
    private javax.swing.JLabel tx_iniciarsesion;
    private javax.swing.JLabel tx_password;
    private javax.swing.JLabel tx_user;
    // End of variables declaration//GEN-END:variables
}
