
import SistemaCine.src.User;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class SignupCine extends javax.swing.JFrame {
    User usuario;
    public SignupCine() {
        initComponents();
        input_password.setBackground(new Color(18,30,49));
        input_password.setForeground(Color.WHITE);
        input_nombre.setBackground(new Color(18,30,49));
        input_nombre.setForeground(Color.WHITE);
        input_apellido.setBackground(new Color(18,30,49));
        input_apellido.setForeground(Color.WHITE);
        input_direccion.setBackground(new Color(18,30,49));
        input_direccion.setForeground(Color.WHITE);
        input_cedula.setBackground(new Color(18,30,49));
        input_cedula.setForeground(Color.WHITE);
        input_correo.setBackground(new Color(18,30,49));
        input_correo.setForeground(Color.WHITE);
        
        usuario=new User();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tx_1 = new javax.swing.JLabel();
        tx_nombre = new javax.swing.JLabel();
        input_nombre = new javax.swing.JTextField();
        tx_apellido = new javax.swing.JLabel();
        input_apellido = new javax.swing.JTextField();
        tx_correo = new javax.swing.JLabel();
        input_correo = new javax.swing.JTextField();
        tx_direccion = new javax.swing.JLabel();
        input_direccion = new javax.swing.JTextField();
        tx_cedula = new javax.swing.JLabel();
        input_cedula = new javax.swing.JTextField();
        tx_password = new javax.swing.JLabel();
        input_password = new javax.swing.JTextField();
        Logo = new javax.swing.JLabel();
        tx_descripcion = new javax.swing.JLabel();
        register_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        tx_1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        tx_1.setForeground(new java.awt.Color(255, 204, 102));
        tx_1.setText("Registrate en nuestro cine");

        tx_nombre.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        tx_nombre.setForeground(new java.awt.Color(255, 204, 102));
        tx_nombre.setText("Nombre:");

        input_nombre.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        input_nombre.setForeground(new java.awt.Color(255, 255, 255));
        input_nombre.setText("Ingrese solo su primer nombre");
        input_nombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        input_nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_nombreMousePressed(evt);
            }
        });
        input_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nombreActionPerformed(evt);
            }
        });

        tx_apellido.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        tx_apellido.setForeground(new java.awt.Color(255, 204, 102));
        tx_apellido.setText("Apellido:");

        input_apellido.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        input_apellido.setForeground(new java.awt.Color(255, 255, 255));
        input_apellido.setText("Ingrese solo su primer apellido");
        input_apellido.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        input_apellido.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_apellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_apellidoMousePressed(evt);
            }
        });

        tx_correo.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        tx_correo.setForeground(new java.awt.Color(255, 204, 102));
        tx_correo.setText("Correo:");

        input_correo.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        input_correo.setForeground(new java.awt.Color(255, 255, 255));
        input_correo.setText("Ingrese su correo");
        input_correo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        input_correo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_correoMousePressed(evt);
            }
        });

        tx_direccion.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        tx_direccion.setForeground(new java.awt.Color(255, 204, 102));
        tx_direccion.setText("Dirección:");

        input_direccion.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        input_direccion.setForeground(new java.awt.Color(255, 255, 255));
        input_direccion.setText("Ejm: Vargas y Caldas");
        input_direccion.setToolTipText("");
        input_direccion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        input_direccion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_direccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_direccionMousePressed(evt);
            }
        });

        tx_cedula.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        tx_cedula.setForeground(new java.awt.Color(255, 204, 102));
        tx_cedula.setText("Cedula:");

        input_cedula.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        input_cedula.setForeground(new java.awt.Color(255, 255, 255));
        input_cedula.setText("Ingrese su cedula");
        input_cedula.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        input_cedula.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_cedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_cedulaMousePressed(evt);
            }
        });

        tx_password.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        tx_password.setForeground(new java.awt.Color(255, 204, 102));
        tx_password.setText("Contraseña:");

        input_password.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        input_password.setForeground(new java.awt.Color(255, 255, 255));
        input_password.setText("Ingrese la contraseña para su cuenta");
        input_password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        input_password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_passwordMousePressed(evt);
            }
        });

        Logo.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        Logo.setForeground(new java.awt.Color(255, 204, 102));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Logo.png"))); // NOI18N
        Logo.setText("Cine Andino");

        tx_descripcion.setFont(new java.awt.Font("Cambria Math", 3, 14)); // NOI18N
        tx_descripcion.setForeground(new java.awt.Color(255, 102, 102));
        tx_descripcion.setText("\"Donde la experiencia es de otro mundo...\"");

        register_button.setBackground(new java.awt.Color(255, 51, 51));
        register_button.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        register_button.setForeground(new java.awt.Color(255, 204, 102));
        register_button.setText("Registrarse");
        register_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        register_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(input_apellido)
                                .addComponent(input_nombre)
                                .addComponent(input_correo)
                                .addComponent(tx_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(input_direccion)
                                .addComponent(tx_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(input_cedula)
                                .addComponent(tx_password, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(input_password, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tx_1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tx_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tx_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tx_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tx_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(register_button, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tx_descripcion)
                .addGap(30, 30, 30)
                .addComponent(tx_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tx_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tx_apellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx_direccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx_cedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tx_correo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tx_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input_password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(register_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Cine.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nombreActionPerformed

    private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
        usuario.setNombre(input_nombre.getText());
        usuario.setApellido(input_apellido.getText());
        usuario.setDireccion(input_direccion.getText());
        usuario.setCedula(input_cedula.getText());
        usuario.setCorreo(input_correo.getText());
        usuario.setContrasena(input_password.getText());
        
        if ( usuario.validarCedula()) {
        } else {
            JOptionPane.showMessageDialog(
                null, 
                "Cédula inválida. Por favor, ingrese una cédula válida.", 
                "Error de Validación", 
                JOptionPane.ERROR_MESSAGE
            );
            input_cedula.setText("");
            input_cedula.requestFocus();
        }
        if (usuario.validarCorreo()){
            JOptionPane.showMessageDialog(
                null, 
                "Correo inválido. Por favor, ingrese un correo valido.", 
                "Error de Validación", 
                JOptionPane.ERROR_MESSAGE
            );
            input_correo.setText("");
            input_correo.requestFocus();
        }
        if(input_nombre.getText().isEmpty() && input_apellido.getText().isEmpty() &&
                input_direccion.getText().isEmpty() && input_cedula.getText().isEmpty() &&
                input_correo.getText().isEmpty() && input_password.getText().isEmpty() &&
                input_nombre.getText().equals("Ingrese solo su primer nombre") &&
                input_apellido.getText().equals("Ingrese solo su primer apellido") &&
                input_direccion.getText().equals("Ejm: Vargas y Caldas") &&
                input_cedula.getText().equals("Ingrese su cedula") &&
                input_correo.getText().equals("Ingrese su correo") &&
                input_password.getText().equals("Ingrese la contraseña para su cuenta")){
            
            if (usuario.verificarDuplicados()==false) { 
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos correctamente.",
                        "Error de Validación",
                        JOptionPane.ERROR_MESSAGE);
            }   
        }else{
            usuario.guardarEnArchivo();
            LoginCine loginCine = new LoginCine(); 
            dispose(); // Cierra la pantalla actual
            loginCine.setVisible(true);
        }
        
    }//GEN-LAST:event_register_buttonActionPerformed

    private void input_nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_nombreMousePressed
        if(input_nombre.getText().equals("Ingrese solo su primer nombre")){ 
            input_nombre.setText("");
        }
        if(input_apellido.getText().isEmpty()){ 
            input_apellido.setText("Ingrese solo su primer apellido"); 
        }
        if(input_direccion.getText().isEmpty()) { 
            input_direccion.setText("Ejm: Vargas y Caldas"); 
        }
        if(input_cedula.getText().isEmpty()) { 
             input_cedula.setText("Ingrese su cedula"); 
         } 
        if(input_correo.getText().isEmpty()) { 
             input_correo.setText("Ingrese su correo"); 
         }
        if(input_password.getText().isEmpty()){
            input_password.setText("Ingrese la contraseña para su cuenta");
        }
    }//GEN-LAST:event_input_nombreMousePressed

    private void input_apellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_apellidoMousePressed
        if(input_apellido.getText().equals("Ingrese solo su primer apellido")) { 
            input_apellido.setText("");
        }
        if(input_nombre.getText().isEmpty()){ 
            input_nombre.setText("Ingrese solo su primer nombre"); 
        }
        if(input_direccion.getText().isEmpty()) { 
            input_direccion.setText("Ejm: Vargas y Caldas"); 
        }
        if(input_cedula.getText().isEmpty()) { 
            input_cedula.setText("Ingrese su cedula"); 
        }
        if(input_correo.getText().isEmpty()) { 
            input_correo.setText("Ingrese su correo"); 
        }
        if(input_password.getText().isEmpty()) {
            input_password.setText("Ingrese la contraseña para su cuenta");
        }
    }//GEN-LAST:event_input_apellidoMousePressed

    private void input_direccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_direccionMousePressed
        if(input_direccion.getText().equals("Ejm: Vargas y Caldas")) { 
            input_direccion.setText("");
        }   
        if(input_apellido.getText().isEmpty()){ 
            input_apellido.setText("Ingrese solo su primer apellido"); 
        }
        if(input_nombre.getText().isEmpty()){ 
            input_nombre.setText("Ingrese solo su primer nombre"); 
        }
        if(input_cedula.getText().isEmpty()) { 
             input_cedula.setText("Ingrese su cedula"); 
         } 
        if(input_correo.getText().isEmpty()) { 
             input_correo.setText("Ingrese su correo"); 
         }
        if(input_password.getText().isEmpty()){
            input_password.setText("Ingrese la contraseña para su cuenta");
        }
    }//GEN-LAST:event_input_direccionMousePressed

    private void input_cedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_cedulaMousePressed
        if(input_cedula.getText().equals("Ingrese su cedula")) { 
            input_cedula.setText("");
        } 
        if(input_apellido.getText().isEmpty()){ 
            input_apellido.setText("Ingrese solo su primer apellido"); 
        }
        if(input_nombre.getText().isEmpty()){ 
            input_nombre.setText("Ingrese solo su primer nombre"); 
        }
        if(input_direccion.getText().isEmpty()) { 
            input_direccion.setText("Ejm: Vargas y Caldas"); 
        } 
        if(input_correo.getText().isEmpty()) { 
             input_correo.setText("Ingrese su correo"); 
         }
        if(input_password.getText().isEmpty()){
            input_password.setText("Ingrese la contraseña para su cuenta");
        }
    }//GEN-LAST:event_input_cedulaMousePressed

    private void input_correoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_correoMousePressed
        if(input_correo.getText().equals("Ingrese su correo")) { 
            input_correo.setText("");
        } 
        if(input_apellido.getText().isEmpty()){ 
            input_apellido.setText("Ingrese solo su primer apellido"); 
        }
        if(input_nombre.getText().isEmpty()){ 
            input_nombre.setText("Ingrese solo su primer nombre"); 
        }
        if(input_direccion.getText().isEmpty()) { 
            input_direccion.setText("Ejm: Vargas y Caldas"); 
        } 
        if(input_cedula.getText().isEmpty()) { 
             input_cedula.setText("Ingrese su cedula"); 
        } 
        if(input_password.getText().isEmpty()){
            input_password.setText("Ingrese la contraseña para su cuenta");
        }
    }//GEN-LAST:event_input_correoMousePressed

    private void input_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_passwordMousePressed
        if(input_password.getText().equals("Ingrese la contraseña para su cuenta")) { 
            input_password.setText("");
        } 
        if(input_apellido.getText().isEmpty()){ 
            input_apellido.setText("Ingrese solo su primer apellido"); 
        }
        if(input_nombre.getText().isEmpty()){ 
            input_nombre.setText("Ingrese solo su primer nombre"); 
        }
        if(input_direccion.getText().isEmpty()) { 
            input_direccion.setText("Ejm: Vargas y Caldas"); 
        } 
        if(input_cedula.getText().isEmpty()) { 
             input_cedula.setText("Ingrese su cedula"); 
        } 
        if(input_correo.getText().isEmpty()) { 
             input_correo.setText("Ingrese su correo"); 
         }
    }//GEN-LAST:event_input_passwordMousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupCine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField input_apellido;
    private javax.swing.JTextField input_cedula;
    private javax.swing.JTextField input_correo;
    private javax.swing.JTextField input_direccion;
    private javax.swing.JTextField input_nombre;
    private javax.swing.JTextField input_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton register_button;
    private javax.swing.JLabel tx_1;
    private javax.swing.JLabel tx_apellido;
    private javax.swing.JLabel tx_cedula;
    private javax.swing.JLabel tx_correo;
    private javax.swing.JLabel tx_descripcion;
    private javax.swing.JLabel tx_direccion;
    private javax.swing.JLabel tx_nombre;
    private javax.swing.JLabel tx_password;
    // End of variables declaration//GEN-END:variables
}
